# Add this function to $PROFILE in powershell
# function lsd {
#    C:\Users\support\scoop\apps\lsd\current\lsd.exe --config-file C:\Users\support\AppData\Local\nvim\lsd\config.yaml @Args
# }
layout: tree
recursion:
  enabled: true
  depth: 2
total-size: true
indicators: true
blocks:
  - permission
  - size
  - date
  - name

